### ISSUE TITLE
Doesn't work on our own rosbag

### ISSUE THREAD

**Issue by yutouwd** [melhousni/ndt_mapping_localization#3]
Hello,

Thanks for your outstanding work. I have successfully run the demo. But when I try to use our own data, after giving the initial pose and playing the rosbag, it would stop on this interface. The robot doesn't move and the trajectory doesn't update. Could you give some suggestion to fix it?

![Screenshot from 2020-12-21 17-28-36](https://user-images.githubusercontent.com/6382417/102762043-b1bb1680-43b2-11eb-8128-e6c50ba9851c.png)

The following picture is the output by running `roslaunch vehicle_localization map_localization.launch`

![Screenshot from 2020-12-21 17-39-15](https://user-images.githubusercontent.com/6382417/102763095-2e022980-43b4-11eb-80a9-b62f9b0ed212.png)
![Screenshot from 2020-12-21 17-39-37](https://user-images.githubusercontent.com/6382417/102763104-30648380-43b4-11eb-8072-60753f8be490.png)

**Comment by melhousni** [comment]
Hi,
Check if you have set up the topics names correctly in the vehicle_localization.launch file.

**Comment by yutouwd** [comment]
Hi, thanks for your kindly reply.

I have checked the topics names in vehicle_localization/launch/map_localization.launch and rosbag. The lidar and imu topic is the same with yours. But I don't have GPS.

And I have tried several times, sometimes it can run successfully, and sometimes it would stuck after first scan. This is so strange.

Successfully run:
![Screenshot from 2020-12-23 00-39-16](https://user-images.githubusercontent.com/6382417/102977329-ce378a00-453d-11eb-844c-d5c9377d4e46.png)

Stuck after first scan: 
![Screenshot from 2020-12-23 16-45-08](https://user-images.githubusercontent.com/6382417/102977662-430ac400-453e-11eb-9a40-8f06aff8102b.png)

Do you have some idea what cause this?

By the way, why I set the initial pose it would give me an opposite pose?

![Peek 2020-12-23 16-47](https://user-images.githubusercontent.com/6382417/102978040-d5ab6300-453e-11eb-9557-67b45f767d85.gif)

**Comment by melhousni** [comment]
If you don't have GPS then you need to modify the EKF params file [here](https://github.com/melhousni/ndt_mapping_localization/blob/master/src/vehicle_state/params/ekf.yaml) because it expects the GPS input in order to generate a reference odometry measurement for the initial guess. For more info on how to personalize the EKF package, check [here](http://docs.ros.org/en/melodic/api/robot_localization/html/index.html).

**Comment by yutouwd** [comment]
Thank you so much, I will check it.

I have another question. Could this algorithm estimate global localization without specifying the initial pose.

**Comment by melhousni** [comment]
Yes but you need the GPS measurements. (cf. readme)

**Comment by WilliamWoo45** [comment]
Hi! @melhousni 

Firstly, thanks for sharing such great work.
I'm also quite interested in global localization. According to your discussion above, I think that the current version of `ndt_mapping_localization` does **not** support global localization, right? I assume whether the specified initial pose by Rviz or GPS measurements must be given then can `ndt_mapping_localization` starts to work.

I'm very looking forward to see a updated version of `ndt_mapping_localization` with the **global localization** ability, since global localization is a quite powerful and useful function to determine the robot pose when it is lost/kidnapped. The accurate initial pose sometimes can be very **difficult** to obtain (such as GPS-denied).

Thanks and all the best!

Best Regards,
William

**Comment by minqi-source** [comment]
> Thank you so much, I will check it.
> 
> I have another question. Could this algorithm estimate global localization without specifying the initial pose.

I would like to know if you have finally solved the problem of the reverse arrow（without gps）. I hope you can share some suggestions on vehicle_state/params/ekf.yaml. Thanks

**Comment by chowkamlee81** [comment]
@yutouwd  @melhousni 

For the bag file that you have shared, it works few times and doesn't works. There is no trajectory shown and keeps stationary under vehicle_localization. I felt too much strange and iam able to get consistent results/same results every time i run bag file.

Kindly please help. Iam using GPS only.

But when i use rviz for initial 2d pose estimate, it always points in reverse direction/..

Kindly help and do the needful

**Comment by barkindagda** [comment]
> Hi, thanks for your kindly reply.
> 
> I have checked the topics names in vehicle_localization/launch/map_localization.launch and rosbag. The lidar and imu topic is the same with yours. But I don't have GPS.
> 
> And I have tried several times, sometimes it can run successfully, and sometimes it would stuck after first scan. This is so strange.
> 
> Successfully run: ![Screenshot from 2020-12-23 00-39-16](https://user-images.githubusercontent.com/6382417/102977329-ce378a00-453d-11eb-844c-d5c9377d4e46.png)
> 
> Stuck after first scan: ![Screenshot from 2020-12-23 16-45-08](https://user-images.githubusercontent.com/6382417/102977662-430ac400-453e-11eb-9a40-8f06aff8102b.png)
> 
> Do you have some idea what cause this?
> 
> By the way, why I set the initial pose it would give me an opposite pose?
> 
> ![Peek 2020-12-23 16-47](https://user-images.githubusercontent.com/6382417/102978040-d5ab6300-453e-11eb-9557-67b45f767d85.gif) [ ![Peek 2020-12-23 16-47](https://user-images.githubusercontent.com/6382417/102978040-d5ab6300-453e-11eb-9557-67b45f767d85.gif) ](https://user-images.githubusercontent.com/6382417/102978040-d5ab6300-453e-11eb-9557-67b45f767d85.gif) [ ](https://user-images.githubusercontent.com/6382417/102978040-d5ab6300-453e-11eb-9557-67b45f767d85.gif)

Hi,

I am using my own data and the it stucks after the first scan too. I have GPS, imu and lidar topics matching with my rosbag but it still stops after 1st scan. Can you please share your solution if you managed to solve this issue.
Many Thanks.
